### ISSUE TITLE
Vanilla docs aren’t searchable

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/vanillaframework.io#105]
1\. Go to the Vanilla site.
2\. Choose “Docs”.
3\. Try to search for a particular pattern.

What happens: There’s no search field.

What should happen: There’s a search field, like there is [for Maas](https://docs.ubuntu.com/maas/2.3/en/) or [for Juju](https://jujucharms.com/docs/stable/getting-started).

(If this bug is reported on the wrong repo, it’s because docs.vanillaframework.io has no report-a-bug link in its footer.)

[Originally reported by @lyubomir-popov during a design meeting.]

**Comment by kwm14** [comment]
Docs are now searchable with our latest release 1.6.6. Search functionality enabled in sidebar navigation, using new search box pattern.

MVP version landed but plan to improve and generate search list as per other documentation sites.

![screen shot 2018-02-28 at 11 57 50](https://user-images.githubusercontent.com/17748020/36786586-d40e5d04-1c7e-11e8-99d2-638974e1f02e.png)
