### ISSUE TITLE
Homepage hero section design exploration 

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/vanillaframework.io#107]
- A new perspective
- Lead with lines ‘Suru’
- Embrace gradients
- Grab attention with colour

**Comment by kwm14** [comment]
## Some good design system examples

- https://vmware.github.io/clarity/
- https://material.io/
- https://www.ibm.com/design/language/

**Comment by kwm14** [comment]
## Current hero section
![screen shot 2017-12-19 at 11 50 01](https://user-images.githubusercontent.com/17748020/34155890-f7362d2e-e4b2-11e7-9698-3cc4b5a9203c.png)

**Comment by kwm14** [comment]
## First visual exploration
- using existing Vanilla patterns
- with/without favicon
- Suru vs Twitter

### 001 - strip light
![vf io-hero-001](https://user-images.githubusercontent.com/17748020/34155587-da1e736e-e4b1-11e7-96af-8aff422c3063.png)

### 002 - strip accent
![vf io-hero-002](https://user-images.githubusercontent.com/17748020/34155588-da45430e-e4b1-11e7-967f-d9c5b7c10164.png)

### 003 - strip image Suru
![vf io-hero-003](https://user-images.githubusercontent.com/17748020/34155589-da675bec-e4b1-11e7-9d6f-f202b98e56af.png)

### 004 - strip image Twitter
![vf io-hero-004](https://user-images.githubusercontent.com/17748020/34155590-da860b32-e4b1-11e7-91d6-c5344e1958cd.png)

**Comment by kwm14** [comment]
## Review with Spencer

- They look good. I think you could try and push it further as this is exploration
- Try some of the colours maybe, your examples all use bright colours. I don't think it matters that they are for caution etc
- What would it look like if you avoided grey? could be interesting
- It's a good opportunity to try some bolder things

**Comment by kwm14** [comment]
## Color
- I explored using our current color palette removing all variations of grey

![color-ways-vanilla](https://user-images.githubusercontent.com/17748020/34206737-b84c8810-e57f-11e7-9840-727d958c615d.png)

- It was interesting to try these colours as they have a high contrast, but this resulted in other elements in the hero to become either invisible or un-accessible
- To go bolder I'm going to explore using our darkest colors: `$color-dark` and `$color-x-dark`

**Comment by kwm14** [comment]
## Further exploration
- taking feedback from @spencerbygraves review
- explored using only `$color-dark` and `$color-x-dark`

### 005
![vf io-hero-005](https://user-images.githubusercontent.com/17748020/34211811-295b309e-e592-11e7-9498-cfcb87e26a42.png)

### 006
![vf io-hero-006](https://user-images.githubusercontent.com/17748020/34211812-297e6f8c-e592-11e7-8771-d35a367c8f16.png)

### 007
![vf io-hero-007](https://user-images.githubusercontent.com/17748020/34211813-29a60038-e592-11e7-81ab-c3452d1f8034.png)

**Comment by anthonydillon** [comment]
006 is gripping but there might be a little to much text.

**Comment by kwm14** [comment]
## Continued further exploration
- Brining hints of Vanilla's color palette into the design
- @anthonydillon mentioned that Tom is working on new Suru folds so will catch up with him in the new year

### 008
![vf io-hero-008a](https://user-images.githubusercontent.com/17748020/34297422-fc52ecde-e70f-11e7-9574-9f5a13347ebe.png)

### 009
![vf io-hero-009](https://user-images.githubusercontent.com/17748020/34297374-b4fe536e-e70f-11e7-8412-d5d53e727d65.png)

### 010
![vf io-hero-010](https://user-images.githubusercontent.com/17748020/34297375-b52307ea-e70f-11e7-8d95-2cc4b5feb693.png)

### 011
![vf io-hero-011](https://user-images.githubusercontent.com/17748020/34297377-b5683e1e-e70f-11e7-8db6-e7b7b6227b0d.png)

**Comment by kwm14** [comment]
## Review with Spencer

- 011 preferred design
- try two more versions; one in black and one in blue
- reduce amount of folds to two in the design
- reduce the angle of the fold that breaks the grid
- include next section to see how it works with hero

**Comment by kwm14** [comment]
## Continued exploration
- taking all feedback into consideration
- two variations of preferred design
- @spencerbygraves ready for review

### 012 - `color-dark` version
![vf io-hero-012](https://user-images.githubusercontent.com/17748020/34779075-0fbb454e-f617-11e7-9e25-5175b4639e15.png)

### 012 - `color-information` version
![vf io-hero-013](https://user-images.githubusercontent.com/17748020/34779322-c3a76114-f617-11e7-866d-503e9c434759.png)

### 013 - `color-dark` version
![vf io-hero-012a](https://user-images.githubusercontent.com/17748020/34779079-1097e8d2-f617-11e7-84ef-6a630b4f9ff9.png)

### 013 - `color-information` version
![vf io-hero-013a](https://user-images.githubusercontent.com/17748020/34779081-116d4252-f617-11e7-8934-856c8dda51fb.png)

**Comment by kwm14** [comment]
### Next steps

- Suru theme workshop with all visual designers to define which backgrounds to use
- Introduce new examples
- Consistency and rational to what/how we use it
