### ISSUE TITLE
Review events implementation on vf.io

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/vanillaframework.io#111]
## Summary

Reviewing pages in Google Analytics I've noticed that bounce rates are at 0.00% which implies that the analytics implementation is almost certainly broken.

Some possible causes:
- Duplicate analytics code
- Incorrectly implemented event tracking

**Comment by anthonydillon** [comment]
Could you give me access to the Google analytics account and I'll take a look.

**Comment by kwm14** [comment]
@anthonydillon Peter just had a quick look and the analytics code isn't duplicated and the event tracking seems to be added correctly.

But we can have a deeper dive and investigate further next week once your free or we can plan it in our next iteration.

**Comment by kwm14** [comment]
Since adding [events](https://github.com/canonical-websites/vanillaframework.io/issues/112) to the homepage 4 weeks ago (even though we didn't push the site live due to technical reasons) I wanted to check that the events were running and to see what users are interested in.

### Events Overview - Total Events: 42
**Event Label**
- See the docs - **66.67%**
- Vanilla on GitHub - **14.29%**
- Download Vanilla Design UI Kit - **9.52%**
- Download Vanilla framework - **9.52%**

Good to see some numbers albeit quite small but I will let it run for another couple of months especially with the recent release of v.1.8.0 and come back and review again.

Promising to see users are Downloading the UI Kit and Framework 👍
