### ISSUE TITLE
Update copyright information in footer

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/vanillaframework.io#113]
## Summary

Update copyright information in footer so it has new year.

## Current and expected result

**Current result**
© 2017 Canonical Ltd. Ubuntu and Canonical are registered trademarks of Canonical Ltd.

**Expected result**
© 2018 Canonical Ltd. Ubuntu and Canonical are registered trademarks of Canonical Ltd.

**Comment by barrymcgee** [comment]
@kwm14 Wierd - this should be dynamic as this value is not hard-coded but uses Jekyll's native date object - https://github.com/canonical-websites/vanillaframework.io/blob/master/_includes/footer.html#L4

**Comment by kwm14** [comment]
@barrymcgee oh really that's cool 👍  maybe I'll clear my cache and see if it updates.

**Comment by barrymcgee** [comment]
@kwm14 It's possible the date on the server is incorrect.. thoughts @nottrobin?

**Comment by nottrobin** [comment]
The copyright notice should *not* track the current year. If you're going to include a year, it should be the year that the notice was first created. But the best solution I think is just to remove the year altogether.

**Comment by nottrobin** [comment]
For more info and references see [the last time I had this discussion](https://github.com/canonical-websites/snapcraft.io/pull/185#discussion_r156872819).

**Comment by nottrobin** [comment]
Also @barrymcgee the reason it hasn't changed is because a *static site* only changes when it's re-generated - i.e. on release. You'd have to do another release to get the year to update. But as mentioned, really you should be either:

- Hard-coding the copyright notice to say 2017; or
- Removing the year from the notice

Otherwise we will be relinquishing copyright over anything we published in 2017.

**Comment by barrymcgee** [comment]
@nottrobin Static site, of course... turkey fog is harder to shift than I thought.

@kwm14 I say we remove it entirely, agree?

**Comment by kwm14** [comment]
@barrymcgee I don't we should remove the year from the footer as it's a pattern we have across all our websites, I'd suggest to hard-code the copyright notice and we manually update each year.

**Comment by barrymcgee** [comment]
@kwm14 So it should now be:

© 2017-18 Canonical Ltd. Ubuntu and Canonical are registered trademarks of Canonical Ltd. ?

**Comment by nottrobin** [comment]
No don't do that. The year represents the year the copyright starts, and then it continues for the maximum term of copyright. Again, if we put "2017-18" then we'll be implying that we aren't interested in copyright after 2018 which isn't accurate.

If we don't dare to remove the year, then it should be:

© 2017 Canonical Ltd. Ubuntu and Canonical are registered trademarks of Canonical Ltd.

**Comment by kwm14** [comment]
@barrymcgee No sorry we should replace 2017 with 2018 so it should be:

 © 2018 Canonical Ltd. Ubuntu and Canonical are registered trademarks of Canonical Ltd.

**Comment by barrymcgee** [comment]
@kwm14 you and @nottrobin need to chat 🧐

**Comment by nottrobin** [comment]
@kwm14 the date in www.ubuntu.com has been written to be dynamic (so it automatically updated to 2018), but I think more by accident than design. I don't think it follows either an official recommendation or intends to set any kind of standard. We shouldn't copy it blindly.

I'm not aware of there being an official policy on this that our websites follow, but I think now that this has come up twice in a month, we should create an official policy. To that end I'm emailed Katherine in legal (and copied in the whole team) to ask if it would be okay to simply remove the year (as [recommended here](http://www.contentious.com/2007/01/07/copyright-notice-is-the-year-really-necessary/)).

Based on her response, I'll create a new document in [the practices repo](https://github.com/canonical-webteam/practices/) to suggest a new standard for the copyright text.

**Comment by barrymcgee** [comment]
Response from legal:

> The year will need to remain as it forms part of the copyright notice required to protect the copyright, along with the copyright symbol and name and owner of the copyright (Canonical Ltd).
> 
> The year, as you mentioned below, relates to the year of first publication. With respect to websites, this will be the year that the page was last updated.

So, in this case, the date in the copyright needs to stay and it should 2018. In terms of what now needs to be done here now, the dynamic variable is already in place to reflect the current year so the next time the site is updated and deployed, the date will be updated also. This issue can now be closed imo.

**Comment by kwm14** [comment]
@barrymcgee we plan to release an update to vf.io next iteration :ok_hand: Thanks
