### ISSUE TITLE
Header is 1px higher on vanillaframework.io than docs.vanillaframework.io

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/vanillaframework.io#116]
On [vanillaframework.io](https://vanillaframework.io/), the header is 48px high.

On [docs.vanillaframework.io](https://docs.vanillaframework.io/en/), the header is 47px high.

What you should see: They should be exactly the same height.

It might be that _if_ the docs.vanillaframework.io header contained any navigation text items (#117), it would be the same height. But it should be the same height regardless.

**Comment by kwm14** [comment]
Thanks @matthewpaulthomas for raising. Update has been fixed with new navigation release in v1.6.6 👍
