### ISSUE TITLE
Header navigation items disappear on docs.vanillaframework.io

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/vanillaframework.io#117]
1\. Go to vanillaframework.io.
2\. In the header, choose “Contribute”.
3\. Choose “Coding standards”.
4\. Choose “Browser support”.
5\. Choose “Accessibility”.
6\. Choose “Docs”.

What happens:
6\. Except for the logo, everything in the header disappears.

What should happen:
6\. The navigation items remain in the header.

**Comment by kwm14** [comment]
Thanks for raising @matthewpaulthomas. Me and @Caleb-Ellis were discussing this yesterday actually and making a plan for it 👍

**Comment by kwm14** [comment]
Update has been fixed with new navigation release in v1.6.6 so that all items in navigation remain.

- https://vanillaframework.io/
