### ISSUE TITLE
Link to submit an issue goes to blank issue template

### ISSUE THREAD

**Issue by yaili** [canonical-websites/vanillaframework.io#173]
## Summary

If you click the link to submit an issue on this page https://vanillaframework.io/contribute it goes to a blank issue page: https://github.com/vanilla-framework/vanilla-framework/issues/new

## Current and expected result

It may be better to link to where you can choose the type of issue: https://github.com/vanilla-framework/vanilla-framework/issues/new/choose

**Comment by anthonydillon** [comment]
@yaili thanks, good spot. Will get this update as soon as possible.
