### ISSUE TITLE
Secondary header pattern

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/vanillaframework.io#194]
ubuntu.com has secondary navigation in the header of many of its pages:

![ubuntu com-community](https://user-images.githubusercontent.com/19801137/51800689-b6104080-222a-11e9-8fa3-db0ee43fc5f4.png)
![ubuntu com-kubernetes](https://user-images.githubusercontent.com/19801137/51800690-b6104080-222a-11e9-930d-270bed5a4a38.png)

design.ubuntu.com also has secondary navigation in the header:
![design ubuntu com-brand](https://user-images.githubusercontent.com/19801137/51800698-d4763c00-222a-11e9-87b1-d406c6bd6e7d.png)

This is broken in at least two ways:
- It falsely presents sibling items as if they are breadcrumbs ([LP#1808827](https://launchpad.net/bugs/1808827))
- The vertical spacing is excessive.

@carlaberkers suggested this could be fixed by introducing a Vanilla pattern for header secondary navigation.

**Comment by kwm14** [comment]
@matthewpaulthomas yes definitely, this is something that can be proposed to Vanilla 💯 

It makes sense to introduce it as a new component seeing that we use it on different sites ans we want consistency across the board.

https://design.ubuntu.com/brand/ example you have above is not ideal 👎 

I will create an issue on https://github.com/ubuntudesign/vanilla-design/ proposing a design for  a secondary header component 👍

**Comment by kwm14** [comment]
Design issue created [here](https://github.com/ubuntudesign/design-vanilla-framework/issues/371). 👍
