### ISSUE TITLE
“Table mobile card” example doesn’t work

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/vanillaframework.io#201]
1\. Open [the “Table mobile card” page](https://docs.vanillaframework.io/en/patterns/table-mobile-card).
2\. Scroll to the example table.
3\. Resize the window to be very narrow.

What happens: Apart from its width, the table appearance does not change.
![vanilla-table-mobile-card](https://user-images.githubusercontent.com/19801137/53000854-91724780-3429-11e9-9eb3-6775733ab159.png)

What should happen: either
- the page should not be present at all, if the pattern no longer exists; or
- the table changes appearance to “a new responsive card” as described.

**Comment by kwm14** [comment]
Thank for raising @matthewpaulthomas 

When filing bugs on Vanilla framework can you create in the correct repo please 😄 thanks!

https://github.com/vanilla-framework/vanilla-framework/issues

**Comment by matthewpaulthomas** [comment]
(I reported it here because I thought it was a bug in the documentation, describing a pattern that no longer exists or has changed its markup.)

**Comment by kwm14** [comment]
@matthewpaulthomas that's fair enough. Recently [Docs](https://github.com/vanilla-framework/vanilla-framework/tree/develop/docs) has merged with the frameworks core codebase. So any future docs bugs will need to be reported [here](https://github.com/vanilla-framework/vanilla-framework/issues) 😄
