### ISSUE TITLE
Update installation instructions and finalise Get started copy

### ISSUE THREAD

**Issue by yaili** [canonical-websites/vanillaframework.io#24]
There are some comments which haven't yet been addressed in the Get started copy doc, that I can't finalise myself. We need this completed asap.

@anthonydillon @nottrobin @barrymcgee could you please have a look at the doc and agree on anything that is still outstanding when you have some time?

Copy doc: https://docs.google.com/document/d/1OJJHIiTVHDKhXCZOStbsJpf2IXVdMkldsTjiq1tUUYw/edit#heading=h.hq7opm8ixxa

**Comment by yaili** [comment]
@anthonydillon @barrymcgee @nottrobin Can I close this now? Is it completed?

**Comment by barrymcgee** [comment]
@yaili No, it's still on my to-do..

**Comment by anthonydillon** [comment]
Considered complete as the Google doc has been confirmed.
