### ISSUE TITLE
Include new pictograms in homepage hero

### ISSUE THREAD

**Issue by yaili** [canonical-websites/vanillaframework.io#33]
Links to assets: https://github.com/ubuntudesign/vanillaframework.io-design/issues/2#issuecomment-311885718

**Comment by yaili** [comment]
@barrymcgee this is done, right?

**Comment by barrymcgee** [comment]
@yaili It's part of the PR above which has not yet landed. 

When that PR does land, it'll close 7 related tickets (referenced in PR) simultaneously.
