### ISSUE TITLE
Improvements to MailChimp

### ISSUE THREAD

**Issue by yaili** [canonical-websites/vanillaframework.io#48]
- [ ] The return to our website link after clicking subscribe should link to vanillaframework.io instead of canonical.com - [reference](http://kb.mailchimp.com/lists/signup-forms/change-or-update-the-return-to-our-website-button)
- [ ] It would be good if the form was changed after pressing subscribe, whether via the return to website link in the confirmation screen, or by returning to the already open tab - at least clearing the email from the input field would be good

**Comment by bartaz** [comment]
Return link updated to https://vanillaframework.io in MailChimp settings.

**Comment by anthonydillon** [comment]
Which URL are we returning to? Could we add a hash to the returned URL to
link to the form and we can use target to display a thank you instead of
the form?

**Comment by bartaz** [comment]
@anthonydillon Currently URL is https://vanillaframework.io but we can add some target to it.

Not sure if 'thank you' will always be relevant, because users returning to our page doesn't mean they completed subscribing (they still need to confirm it in email).

**Comment by anthonydillon** [comment]
Ok fair enough.

**Comment by bartaz** [comment]
@anthonydillon MailChimp provides embedded form with JavaScript (http://kb.mailchimp.com/lists/signup-forms/add-a-signup-form-to-your-website)  that can submit via AJAX and show errors/response inline in the form.

We can investigate this option, but their custom form may not be fully in line with Vanilla styles for showing inputs and errors etc.
