### ISSUE TITLE
Returning to vf.io from vf.io/docs

### ISSUE THREAD

**Issue by Lukewh** [canonical-websites/vanillaframework.io#57]
## Summary

Should docs logo should link back to vf.io and the 'Documentation' link to the docs homepage?

## Process

Go to docs.

## Current and expected result

When you go to docs there's no way back to vanillaframework.io.

**Comment by yaili** [comment]
I think this issue would resolve it: https://github.com/vanilla-framework/vanilla-docs-theme/issues/22 - it has been in the current iteration for the past 2 iterations.

**Comment by barrymcgee** [comment]
This is now resolved.
