### ISSUE TITLE
Update 'Get started' CTA label and link on homepage

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/vanillaframework.io#61]
## Summary

Update 'Get started' CTA button to point to Vanilla documentation rather than anchor scrolling down one row on homepage. Also update button label to read 'See the docs'

## Current and expected result

- Current result - 'Get started' anchor scrolls to 'Quick start' on same page. Current button label 'Get started'
- Expected result - 'Get started' to send users to Vanilla documentation. Expected button label 'See the docs'

**Comment by yaili** [comment]
@kwm14 should it say "See the docs" or something that is more informative of what you'll get?
