### ISSUE TITLE
“Quick start” nav link and “Get started” button don’t work

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/vanillaframework.io#69]
1\. Go to [the front page](https://vanillaframework.io/).
2\. In the header click “Quick start”.
3\. On the front page click “Get started”.

What happens:
2\. Nothing.
3\. Nothing.

What should happen:
2\. The page scrolls to the “Quick start” section.
3\. The page scrolls to the “Quick start” section.

This is apparently because they link to “`#quick-start`” but the section only has `id="getting-started"`.

**Comment by anthonydillon** [comment]
These links have been removed and replaced with links to the docs.
