### ISSUE TITLE
Inconsistent underlining on hover of header button vs. header button text

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/vanillaframework.io#70]
1\. Go to any page on vanillaframework.io.
2\. Mouse over the empty part of any of the header buttons.
3\. Mouse over the text in the header button.

What happens:
2\. The text has a thin underline.
3\. The text has a thick underline.

![vanilla-header-underlining-1](https://user-images.githubusercontent.com/19801137/29115226-c8ec1de2-7cee-11e7-8e98-3005e25433d0.gif)

What should happen: either
2\. The text has a thin underline.
3\. The text has a thin underline.

Or
2\. The text has no underline.
3\. The text has no underline.

**Comment by yaili** [comment]
@barrymcgee @anthonydillon didn't @bartaz fix this issue during our mini-sprint? For me, on Chrome I don't see the different weights of underline as the mouse moves, but the links are not clickable until the cursor becomes a hand. I thought this had been fixed.

**Comment by barrymcgee** [comment]
@yaili It has been fixed upstream - just hasn't made it down to vf.io. Once we release Vanilla on Monday with VBT absorbed, we can then pull vanilla directly into vf.io to address this.
