### ISSUE TITLE
add GTM to the site(s)

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/vanillaframework.io#71]
Install Google Tag Manager
Copy the code below and paste it onto every page of your website.
Paste this code as high in the <head> of the page as possible:

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-K7ZB6FL');</script>
<!-- End Google Tag Manager -->
```

Additionally, paste this code immediately after the opening <body> tag:

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-K7ZB6FL"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

For more information about installing the Google Tag Manager snippet, visit our Quick Start Guide .

**Comment by anthonydillon** [comment]
@pmahnke I don't seem to have access to the GTM container (GTM-K7ZB6FL). Could you share please so we can switch on GA please?
