### ISSUE TITLE
Update copy doc to reflect changes in hero copy

### ISSUE THREAD

**Issue by yaili** [canonical-websites/vanillaframework.io#75]
There was a PR to review copy updates in the middle column of the hero extendable --> composable, but these aren't reflected in the [copy doc](https://drive.google.com/drive/u/1/folders/0B0KGtsOjZL3TMDU3ajlBSDN4aGM). For reference, any copy changes should start there and only then added to code.

Could you update the document? Don't know if it was @barrymcgee or @anthonydillon who created the new copy.

**Comment by barrymcgee** [comment]
Fixed by https://github.com/canonical-websites/vanillaframework.io/pull/73
