### ISSUE TITLE
Build homepage skeleton

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/vanillaframework.io#8]
https://github.com/ubuntudesign/vanillaframework.io-design/issues/1

**Comment by barrymcgee** [comment]
Just a reminder that the master branch of this repo already has a skeleton homepage to iterate on. 

![fireshot capture 1 - vanilla framework - http___localhost_3000_](https://cloud.githubusercontent.com/assets/505570/24302209/c9666c5c-10a9-11e7-9599-78e080f23127.png)

**Comment by anthonydillon** [comment]
Yeah will evolve it, is really to update the layout to the new design.
