### ISSUE TITLE
update cert on docs.vf.io

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/vanillaframework.io#83]
## Summary

* https giving error, cert expired yesterday

## Screenshot

![image](https://user-images.githubusercontent.com/441217/30732964-d0c5e750-9f6c-11e7-9b87-2a9e5bec0b3d.png)

**Comment by WillMoggridge** [comment]
This has been updated now. The renewal was failing because it included a check with vanillaframework.io and that has changed hosts.
