### ISSUE TITLE
Add crazy egg to vanillaframework.io

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/vanillaframework.io#84]
## Summary

We need to add Crazy egg to vanillaframework.io which provide heatmaps and will help with A/B testing of new sections and give insight to know what is/isn't working on the site.

https://www.crazyegg.com/

Please add the following tracking script to all pages:

```
<script type="text/javascript" src="//script.crazyegg.com/pages/scripts/0011/8875.js" async="async"></script>
```

**Comment by barrymcgee** [comment]
@kwm14 Can you sign up and add the code snippet CrazyEgg provides to this issue?

**Comment by kwm14** [comment]
@barrymcgee sure thing, I believe we have a CrazyEgg account so will find credentials and create a snapshot for [vanillaframework.io](url)

**Comment by anthonydillon** [comment]
We have a corp account. Which we control via GTM.

**Comment by kwm14** [comment]
@barrymcgee @anthonydillon 

**Tracking script**
<script type="text/javascript" src="//script.crazyegg.com/pages/scripts/0011/8875.js" async="async"></script>

**Comment by kwm14** [comment]
Creating a new issue which has a clear breakdown of this task needing to be complete.
