### ISSUE TITLE
Add more logos of migrated sites using Vanilla

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/vanillaframework.io#86]
## Summary

Add more product logos to 'Who's using Vanilla' section on the homepage of the website.

## Process

We've migrated more sites to use Vanilla so let's promote them. 
- conjure-up - https://assets.ubuntu.com/v1/8c237d84-conjure-up-logo-black.svg
- snapcraft.io - https://assets.ubuntu.com/v1/d45097a4-snapcraft.io-logotype.svg
- cloud-init - https://assets.ubuntu.com/v1/dde48684-cloud-init_black-orange_hex.svg
 
## Screenshot
![screen shot 2017-10-17 at 14 10 41](https://user-images.githubusercontent.com/17748020/31666668-fdd8f5f2-b344-11e7-8467-3071bd3e5e50.png)

**Comment by uokesita** [comment]
I'll do this

**Comment by kwm14** [comment]
Thanks for your contribution @uokesita 👍
