### ISSUE TITLE
Replace cloud-init logo with updated horizontal version

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/vanillaframework.io#89]
## Summary

Replace cloud-init logo with updated version on homepage of vanillaframework.io

## Process

- Go to https://vanillaframework.io/
- Scroll to 'WHO’S USING VANILLA' section
- Update existing cloud-init logo with updated version supplied below

## Updated logo asset

- https://assets.ubuntu.com/v1/640864f3-cloud-init-logo.svg

**Comment by virenb** [comment]
I'll give this a try
