### ISSUE TITLE
Broken/missing links in Guidelines section

### ISSUE THREAD

**Issue by sparkiegeek** [canonical-websites/vanillaframework.io#97]
## Summary

Broken Guideline links on homepage

## Process

1. Load vanillaframework.io (tested in both Firefox and Chromium)
2. Scroll down to Guideline section
3. Le click

## Current and expected result

Current behaviour is that they're a link to vanillaframework.io so I get jumped to the top of the page

Expected behaviour is that I see a page or section expanded relevant to the thing I clicked.

## Screenshot
N/A

**Comment by anthonydillon** [comment]
Thanks @sparkiegeek. Your right. The links should be to the pages not to the same page.

**Comment by jamieburnip** [comment]
PR requested - https://github.com/canonical-websites/vanillaframework.io/pull/98
